enum constants {
    GET_BLOGS = 'GET_BLOGS',
    GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS',
    GET_BLOG_FAILURE = 'GET_BLOG_FAILURE',
    GET_BLOG_CANCEL = 'GET_BLOG_CANCEL',
    CREATE_BLOG = 'CREATE_BLOG',
    CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS',
    CREATE_BLOG_FAILURE = 'CREATE_BLOG_FAILURE'
}

export default constants
