enum constants {
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',
    GET_CURRENT_USER = 'GET_CURRENT_USER',
    GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS',
    GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE',
    LOGOUT = 'LOGOUT'
}

export default constants
